version: '3'
services:
  db:
    image: mysql
    ports:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=secret
      - MYSQL_USER=secret
      - MYSQL_PASSWORD=secret
  api:
    build: .
    image: "example_news_api:example_news_api"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    restart: always
    expose:
      - "3000"