FROM python:3.6

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

ADD . /app
WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 3000

CMD ["./run.sh"]