FROM python:3.6

ADD . /app
WORKDIR /app

# ensure python to target this app
ENV PATH=$PATH:/app
ENV PYTHONPATH /app

RUN pip install -r requirements.txt

CMD gunicorn --bind 0.0.0.0:$PORT manage:start