FROM nginx:stable

COPY default.conf.template-stag /etc/nginx/conf.d/default.conf.template-stag

COPY . /usr/share/nginx/html

CMD /bin/bash -c "envsubst \\\$PORT < /etc/nginx/conf.d/default.conf.template-stag > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"